terminal_source: ''
software_timer:
  priority: 2
  stack_depth: 1024
USB:
  usb_otg_fs:
    enable: true
    ep0_packet_size: 8
    tx_buffer_size: 128
    rx_buffer_size: 128
    rx_fifo_size: 256
    tx_fifo_size: 128
    dma_section: ''
    cdc_tx_fifo_size: 128
    cdc_rx_fifo_size: 128
    cdc_queue_size: 3
    vid: 7504
    pid: 24985
    bcd: 256
    manufacturer: XRobot
    product: STM32 XRUSB USB_OTG_FS CDC Demo
    serial: XRUSB-DEMO-
  usb_otg_hs:
    enable: false
Terminal:
  read_buff_size: 32
  max_line_size: 32
  max_arg_number: 5
  max_history_number: 5
SYSTEM: FreeRTOS
FlashLayout:
  model: STM32F407ZGT6
  flash_base: '0x08000000'
  flash_size_kb: 1024
  sectors:
  - index: 0
    address: '0x08000000'
    size_kb: 16.0
  - index: 1
    address: '0x08004000'
    size_kb: 16.0
  - index: 2
    address: '0x08008000'
    size_kb: 16.0
  - index: 3
    address: '0x0800C000'
    size_kb: 16.0
  - index: 4
    address: '0x08010000'
    size_kb: 64.0
  - index: 5
    address: '0x08020000'
    size_kb: 128.0
  - index: 6
    address: '0x08040000'
    size_kb: 128.0
  - index: 7
    address: '0x08060000'
    size_kb: 128.0
  - index: 8
    address: '0x08080000'
    size_kb: 128.0
  - index: 9
    address: '0x080A0000'
    size_kb: 128.0
  - index: 10
    address: '0x080C0000'
    size_kb: 128.0
  - index: 11
    address: '0x080E0000'
    size_kb: 128.0
